### ISSUE TITLE
AttributeError: module 'osr' has no attribute 'SRS_WKT_WGS84'

### ISSUE THREAD

**Issue by Linkersem** [nansencenter/sea_ice_drift#23]
I try to run this simple. py program, but the following problems encountered in the process of operation. (which I use `conda install - channel https://conda.anaconda.org/conda-forge nansat` to install nansat package)

DLL load failed: 找不到指定的模块。
D:\ANACONDA\envs\py3drift11\lib\site-packages\nansat\__init__.py:35: UserWarning: Cannot register C pixel functions!
                     Either nansat was not installed using setup.py or
                     pixel functions were not compiled automatically.
                     For development, use "python setup.py build_ext --inplace"
                     to compile pixel functions manually into the source tree.
                     
  ''')
D:\ANACONDA\envs\py3drift11\lib\site-packages\nansat\tools.py:120: MatplotlibDeprecationWarning: Passing raw data via parameters data and lut to register_cmap() is deprecated since 3.3 and will become an error two minor releases later. Instead use: register_cmap(cmap=LinearSegmentedColormap(name, data, lut))
  cm.register_cmap(name='obpg', data=obpg, lut=256)
D:\ANACONDA\envs\py3drift11\lib\site-packages\nansat\tools.py:121: MatplotlibDeprecationWarning: Passing raw data via parameters data and lut to register_cmap() is deprecated since 3.3 and will become an error two minor releases later. Instead use: register_cmap(cmap=LinearSegmentedColormap(name, data, lut))
  cm.register_cmap(name='ak01', data=ak01, lut=256)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\ANACONDA\envs\py3drift11\lib\site-packages\nansat\__init__.py", line 37, in <module>
    from nansat.domain import Domain
  File "D:\ANACONDA\envs\py3drift11\lib\site-packages\nansat\domain.py", line 25, in <module>
    from nansat.vrt import VRT
  File "D:\ANACONDA\envs\py3drift11\lib\site-packages\nansat\vrt.py", line 31, in <module>
    from nansat.geolocation import Geolocation
  File "D:\ANACONDA\envs\py3drift11\lib\site-packages\nansat\geolocation.py", line 22, in <module>
    class Geolocation(object):
  File "D:\ANACONDA\envs\py3drift11\lib\site-packages\nansat\geolocation.py", line 61, in Geolocation
    def _init_data(self, x_filename, y_filename, x_band=1, y_band=1, srs=NSR().wkt,
  File "D:\ANACONDA\envs\py3drift11\lib\site-packages\nansat\nsr.py", line 66, in __init__
    status = self.ImportFromWkt(osr.SRS_WKT_WGS84)
AttributeError: module 'osr' has no attribute 'SRS_WKT_WGS84'

I don't know how to solve this problem. Thank you very much for your help.

**Comment by akorosov** [comment]
Version of nansat on conda forge is quite outdated. Please follow the new instructions:
https://github.com/nansencenter/nansat#installation

**Comment by Miracle-linker** [comment]
Thank you for your reply. I have tried the method mentioned in the link you sent before, but there was an error. I have tried many methods but failed to solve the problem, the error is as follows:

```
Building wheels for collected packages: gdal
  Building wheel for gdal (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\ANACONDA\envs\py3drift11\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\12855\\AppData\\Local\\Temp\\pip-install-i60ib62z\\gdal\\setup.py'"'"'; __file__='"'"'C:\\Users\\12855\\AppData\\Local\\Temp\\pip-install-i60ib62z\\gdal\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\12855\AppData\Local\Temp\pip-wheel-kgy1m_xu'
       cwd: C:\Users\12855\AppData\Local\Temp\pip-install-i60ib62z\gdal\
  Complete output (34 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  copying gdal.py -> build\lib.win-amd64-3.6
  copying ogr.py -> build\lib.win-amd64-3.6
  copying osr.py -> build\lib.win-amd64-3.6
  copying gdalconst.py -> build\lib.win-amd64-3.6
  copying gdalnumeric.py -> build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\osgeo
  copying osgeo\gdal.py -> build\lib.win-amd64-3.6\osgeo
  copying osgeo\gdalconst.py -> build\lib.win-amd64-3.6\osgeo
  copying osgeo\gdalnumeric.py -> build\lib.win-amd64-3.6\osgeo
  copying osgeo\gdal_array.py -> build\lib.win-amd64-3.6\osgeo
  copying osgeo\gnm.py -> build\lib.win-amd64-3.6\osgeo
  copying osgeo\ogr.py -> build\lib.win-amd64-3.6\osgeo
  copying osgeo\osr.py -> build\lib.win-amd64-3.6\osgeo
  copying osgeo\__init__.py -> build\lib.win-amd64-3.6\osgeo
  D:\ANACONDA\envs\py3drift11\lib\site-packages\setuptools\lib2to3_ex.py:44: SetuptoolsDeprecationWarning: 2to3 support is deprecated. If the project still requires Python 2 support, please migrate to a single-codebase solution or employ an independent conversion process.
    SetuptoolsDeprecationWarning)
  Fixing build\lib.win-amd64-3.6\gdal.py build\lib.win-amd64-3.6\ogr.py build\lib.win-amd64-3.6\osr.py build\lib.win-amd64-3.6\gdalconst.py build\lib.win-amd64-3.6\gdalnumeric.py build\lib.win-amd64-3.6\osgeo\gdal.py build\lib.win-amd64-3.6\osgeo\gdalconst.py build\lib.win-amd64-3.6\osgeo\gdalnumeric.py build\lib.win-amd64-3.6\osgeo\gdal_array.py build\lib.win-amd64-3.6\osgeo\gnm.py build\lib.win-amd64-3.6\osgeo\ogr.py build\lib.win-amd64-3.6\osgeo\osr.py build\lib.win-amd64-3.6\osgeo\__init__.py
  Skipping optional fixer: ws_comma
  Fixing build\lib.win-amd64-3.6\gdal.py build\lib.win-amd64-3.6\ogr.py build\lib.win-amd64-3.6\osr.py build\lib.win-amd64-3.6\gdalconst.py build\lib.win-amd64-3.6\gdalnumeric.py build\lib.win-amd64-3.6\osgeo\gdal.py build\lib.win-amd64-3.6\osgeo\gdalconst.py build\lib.win-amd64-3.6\osgeo\gdalnumeric.py build\lib.win-amd64-3.6\osgeo\gdal_array.py build\lib.win-amd64-3.6\osgeo\gnm.py build\lib.win-amd64-3.6\osgeo\ogr.py build\lib.win-amd64-3.6\osgeo\osr.py build\lib.win-amd64-3.6\osgeo\__init__.py
  Skipping optional fixer: ws_comma
  running build_ext
  building 'osgeo._gdal' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\extensions
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\ANACONDA\envs\py3drift11\include -ID:\ANACONDA\envs\py3drift11\include -ID:\ANACONDA\envs\py3drift11\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpextensions/gdal_wrap.cpp /Fobuild\temp.win-amd64-3.6\Release\extensions/gdal_wrap.obj
  gdal_wrap.cpp
  extensions/gdal_wrap.cpp(3173): fatal error C1083: 无法打开包括文件: “cpl_port.h”: No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for gdal
  Running setup.py clean for gdal
Failed to build gdal
DEPRECATION: Could not build wheels for gdal which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: gdal, nansat
  Attempting uninstall: gdal
    Found existing installation: gdal 3.1.2
    Uninstalling gdal-3.1.2:
      Successfully uninstalled gdal-3.1.2
    Running setup.py install for gdal ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\ANACONDA\envs\py3drift11\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\12855\\AppData\\Local\\Temp\\pip-install-i60ib62z\\gdal\\setup.py'"'"'; __file__='"'"'C:\\Users\\12855\\AppData\\Local\\Temp\\pip-install-i60ib62z\\gdal\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\12855\AppData\Local\Temp\pip-record-l7pvazb7\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\ANACONDA\envs\py3drift11\Include\gdal'
         cwd: C:\Users\12855\AppData\Local\Temp\pip-install-i60ib62z\gdal\
    Complete output (34 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    copying gdal.py -> build\lib.win-amd64-3.6
    copying ogr.py -> build\lib.win-amd64-3.6
    copying osr.py -> build\lib.win-amd64-3.6
    copying gdalconst.py -> build\lib.win-amd64-3.6
    copying gdalnumeric.py -> build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\osgeo
    copying osgeo\gdal.py -> build\lib.win-amd64-3.6\osgeo
    copying osgeo\gdalconst.py -> build\lib.win-amd64-3.6\osgeo
    copying osgeo\gdalnumeric.py -> build\lib.win-amd64-3.6\osgeo
    copying osgeo\gdal_array.py -> build\lib.win-amd64-3.6\osgeo
    copying osgeo\gnm.py -> build\lib.win-amd64-3.6\osgeo
    copying osgeo\ogr.py -> build\lib.win-amd64-3.6\osgeo
    copying osgeo\osr.py -> build\lib.win-amd64-3.6\osgeo
    copying osgeo\__init__.py -> build\lib.win-amd64-3.6\osgeo
    D:\ANACONDA\envs\py3drift11\lib\site-packages\setuptools\lib2to3_ex.py:44: SetuptoolsDeprecationWarning: 2to3 support is deprecated. If the project still requires Python 2 support, please migrate to a single-codebase solution or employ an independent conversion process.
      SetuptoolsDeprecationWarning)
    Fixing build\lib.win-amd64-3.6\gdal.py build\lib.win-amd64-3.6\ogr.py build\lib.win-amd64-3.6\osr.py build\lib.win-amd64-3.6\gdalconst.py build\lib.win-amd64-3.6\gdalnumeric.py build\lib.win-amd64-3.6\osgeo\gdal.py build\lib.win-amd64-3.6\osgeo\gdalconst.py build\lib.win-amd64-3.6\osgeo\gdalnumeric.py build\lib.win-amd64-3.6\osgeo\gdal_array.py build\lib.win-amd64-3.6\osgeo\gnm.py build\lib.win-amd64-3.6\osgeo\ogr.py build\lib.win-amd64-3.6\osgeo\osr.py build\lib.win-amd64-3.6\osgeo\__init__.py
    Skipping optional fixer: ws_comma
    Fixing build\lib.win-amd64-3.6\gdal.py build\lib.win-amd64-3.6\ogr.py build\lib.win-amd64-3.6\osr.py build\lib.win-amd64-3.6\gdalconst.py build\lib.win-amd64-3.6\gdalnumeric.py build\lib.win-amd64-3.6\osgeo\gdal.py build\lib.win-amd64-3.6\osgeo\gdalconst.py build\lib.win-amd64-3.6\osgeo\gdalnumeric.py build\lib.win-amd64-3.6\osgeo\gdal_array.py build\lib.win-amd64-3.6\osgeo\gnm.py build\lib.win-amd64-3.6\osgeo\ogr.py build\lib.win-amd64-3.6\osgeo\osr.py build\lib.win-amd64-3.6\osgeo\__init__.py
    Skipping optional fixer: ws_comma
    running build_ext
    building 'osgeo._gdal' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\extensions
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\ANACONDA\envs\py3drift11\include -ID:\ANACONDA\envs\py3drift11\include -ID:\ANACONDA\envs\py3drift11\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpextensions/gdal_wrap.cpp /Fobuild\temp.win-amd64-3.6\Release\extensions/gdal_wrap.obj
    gdal_wrap.cpp
    extensions/gdal_wrap.cpp(3173): fatal error C1083: 无法打开包括文件: “cpl_port.h”: No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
  Rolling back uninstall of gdal
  Moving to d:\anaconda\envs\py3drift11\lib\site-packages\__pycache__\gdal.cpython-36.pyc
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4_ruc48u\gdal.cpython-36.pyc
  Moving to d:\anaconda\envs\py3drift11\lib\site-packages\__pycache__\ogr.cpython-36.pyc
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4_ruc48u\ogr.cpython-36.pyc
  Moving to d:\anaconda\envs\py3drift11\lib\site-packages\__pycache__\osr.cpython-36.pyc
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4_ruc48u\osr.cpython-36.pyc
  Moving to d:\anaconda\envs\py3drift11\lib\site-packages\gdal-3.1.2-py3.6-win-amd64.egg-info
   from d:\anaconda\envs\py3drift11\lib\site-packages\~dal-3.1.2-py3.6-win-amd64.egg-info
  Moving to d:\anaconda\envs\py3drift11\lib\site-packages\gdal.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-8kk0fas2\gdal.py
  Moving to d:\anaconda\envs\py3drift11\lib\site-packages\gdalconst.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-8kk0fas2\gdalconst.py
  Moving to d:\anaconda\envs\py3drift11\lib\site-packages\gdalnumeric.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-8kk0fas2\gdalnumeric.py
  Moving to d:\anaconda\envs\py3drift11\lib\site-packages\ogr.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-8kk0fas2\ogr.py
  Moving to d:\anaconda\envs\py3drift11\lib\site-packages\osgeo
   from d:\anaconda\envs\py3drift11\lib\site-packages\~sgeo
  Moving to d:\anaconda\envs\py3drift11\lib\site-packages\osr.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-8kk0fas2\osr.py
  Moving to d:\anaconda\envs\py3drift11\scripts\epsg_tr.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\epsg_tr.py
  Moving to d:\anaconda\envs\py3drift11\scripts\esri2wkt.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\esri2wkt.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gcps2vec.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gcps2vec.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gcps2wld.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gcps2wld.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdal2tiles.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdal2tiles.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdal2xyz.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdal2xyz.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdal_auth.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdal_auth.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdal_calc.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdal_calc.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdal_edit.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdal_edit.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdal_fillnodata.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdal_fillnodata.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdal_merge.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdal_merge.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdal_pansharpen.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdal_pansharpen.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdal_polygonize.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdal_polygonize.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdal_proximity.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdal_proximity.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdal_retile.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdal_retile.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdal_sieve.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdal_sieve.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdalchksum.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdalchksum.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdalcompare.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdalcompare.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdalident.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdalident.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdalimport.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdalimport.py
  Moving to d:\anaconda\envs\py3drift11\scripts\gdalmove.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\gdalmove.py
  Moving to d:\anaconda\envs\py3drift11\scripts\mkgraticule.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\mkgraticule.py
  Moving to d:\anaconda\envs\py3drift11\scripts\ogrmerge.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\ogrmerge.py
  Moving to d:\anaconda\envs\py3drift11\scripts\pct2rgb.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\pct2rgb.py
  Moving to d:\anaconda\envs\py3drift11\scripts\rgb2pct.py
   from C:\Users\12855\AppData\Local\Temp\pip-uninstall-4k6aetyg\rgb2pct.py
ERROR: Command errored out with exit status 1: 'D:\ANACONDA\envs\py3drift11\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\12855\\AppData\\Local\\Temp\\pip-install-i60ib62z\\gdal\\setup.py'"'"'; __file__='"'"'C:\\Users\\12855\\AppData\\Local\\Temp\\pip-install-i60ib62z\\gdal\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\12855\AppData\Local\Temp\pip-record-l7pvazb7\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\ANACONDA\envs\py3drift11\Include\gdal' Check the logs for full command output.
```

**Comment by Miracle-linker** [comment]
Hi @akorosov  I have solved the above problem, which was caused by the high level of gDAL release,When `conda cret-q -- yes-n py3driftfinal-c conda-forge Python =3.6 numpy Scipy Matplotlib NetcdF4 Gdal Opencv nose `is changed to `Conda cret-q -- yes-n py3driftfinal-C Conda-forge Python =3.6 numpy ScipyAfter Matplotlib netcdF4 gdal=2.4.4 Opencv nose` .The problem disappeared and the test program was successfully run.
In addition, I want to try to process my own Sentinel-1 SAR images.Could you please tell me what needs to be modified according to my own data?
