### ISSUE TITLE
json update needed

### ISSUE THREAD

**Issue by loniitkina** [nansencenter/sea_ice_drift#27]
The code does not work with the latest Nansat version. The package was installed with conda.

Here the output:
/Data/pit000/ResearchData/IFT/EarthObservation/MOSAIC/SAR/Sentinel-1/S1B_EW_GRDM_1SDH_20191016T064336_20191016T064441_018497_022DA3_6888.zip
/Data/pit000/ResearchData/IFT/EarthObservation/MOSAIC/SAR/Sentinel-1/S1B_EW_GRDM_1SDH_20191017T040823_20191017T040927_018510_022E09_9E76.zip
20191016T064336 20191017T040823
Time difference: 77087.0 seconds
07:39:54|40|nansat|_get_dataset_metadata|GDAL could not open /Data/pit000/ResearchData/IFT/EarthObservation/MOSAIC/SAR/Sentinel-1/S1B_EW_GRDM_1SDH_20191016T064336_20191016T064441_018497_022DA3_6888.zip, trying to read with Nansat mappers...
Traceback (most recent call last):
  File "sid_drift.py", line 147, in <module>
    sid = SeaIceDrift(f1, f2)
  File "/home/pit000/miniconda3/envs/py3drift/lib/python3.6/site-packages/sea_ice_drift/seaicedrift.py", line 38, in __init__
    self.n1 = get_n(self.filename1, **kwargs)
  File "/home/pit000/miniconda3/envs/py3drift/lib/python3.6/site-packages/sea_ice_drift/lib.py", line 210, in get_n
    n = Nansat(filename)
  File "/home/pit000/miniconda3/envs/py3drift/lib/python3.6/site-packages/nansat/nansat.py", line 159, in __init__
    self.vrt = self._get_mapper(mapper, **kwargs)
  File "/home/pit000/miniconda3/envs/py3drift/lib/python3.6/site-packages/nansat/nansat.py", line 1164, in _get_mapper
    tmp_vrt = nansatMappers[iMapper](self.filename, gdal_dataset, metadata, **kwargs)
  File "/home/pit000/miniconda3/envs/py3drift/lib/python3.6/site-packages/nansat/mappers/mapper_cmems.py", line 38, in __init__
    gcmd_keywords_mapping = get_gcmd_keywords_mapping()
  File "/home/pit000/miniconda3/envs/py3drift/lib/python3.6/site-packages/nansat/mappers/mapper_cmems.py", line 16, in get_gcmd_keywords_mapping
    'instrument': json.dumps(pti.get_gcmd_instrument('computer')),
  File "/home/pit000/miniconda3/envs/py3drift/lib/python3.6/site-packages/pythesint/vocabulary.py", line 45, in find_keyword
    for d in self.get_list():
  File "/home/pit000/miniconda3/envs/py3drift/lib/python3.6/site-packages/pythesint/json_vocabulary.py", line 22, in get_list
    result = json.load(opened_file)
  File "/home/pit000/miniconda3/envs/py3drift/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/pit000/miniconda3/envs/py3drift/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/pit000/miniconda3/envs/py3drift/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/pit000/miniconda3/envs/py3drift/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by loniitkina** [comment]
@akorosov

**Comment by CatherineTaelman** [comment]
exactly the same issue here, looking forward to a solution:)

**Comment by LeoNull101** [comment]
I have the same problem, I think the reason is my VPN setting, the first time I running it, it download a file automaticly, but because my internet issue, the progress closed in middle way, I think delete the file and redownload it should work, but I don't know where it is.

**Comment by CatherineTaelman** [comment]
as in the S1 denoising algorithm instructions, the metadata vocabulary needs to be updated: 
python -c 'import pythesint as pti; pti.update_all_vocabularies()' . This solved the issue for me.

**Comment by LeoNull101** [comment]
> as in the S1 denoising algorithm instructions, the metadata vocabulary needs to be updated: python -c 'import pythesint as pti; pti.update_all_vocabularies()' . This solved the issue for me.
Fixed my issue, and thanks a lot.

**Comment by bigleaffrog** [comment]
sorry, I still don't konw how to solve this problem.

**Comment by bigleaffrog** [comment]
error“Could not get the vocabulary file at 'https://raw.githubusercontent.com/nansencenter/nersc-vocabularies/master/nansat_wkv.yml'”
